[package]
name = "yew_editor"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@amethyst-engine.org>"]
edition = "2018"

[dependencies]
yew = "0.6"
stdweb = "0.4.12"
web_logger = "0.1"
log = "0.4"
serde = "1.0.85"
serde_derive = "1.0.85"
serde_json = "1.0.37"
failure = "0.1"
